update-package Sitecore.Abstractions.NoReferences
update-package Sitecore.Analytics.Automation.NoReferences
update-package Sitecore.Analytics.Core.NoReferences
update-package Sitecore.Analytics.Model.NoReferences
update-package Sitecore.Analytics.MongoDB.NoReferences
update-package Sitecore.Analytics.NoReferences
update-package Sitecore.Analytics.Outcome.NoReferences
update-package Sitecore.Analytics.Processing.NoReferences
update-package Sitecore.Buckets.NoReferences
update-package Sitecore.CES.DeviceDetection.NoReferences
update-package Sitecore.Cintel.NoReferences
update-package Sitecore.Client.NoReferences
update-package Sitecore.Commerce.NoReferences
update-package Sitecore.ContentSearch.Analytics.NoReferences
update-package Sitecore.ContentSearch.Linq.NoReferences
update-package Sitecore.ContentSearch.Linq.NoReferences
update-package Sitecore.ContentSearch.NoReferences
update-package Sitecore.ContentSearch.NoReferences
update-package Sitecore.ExperienceEditor.NoReferences
update-package Sitecore.ExperienceExplorer.Business.NoReferences
update-package Sitecore.Forms.Core.NoReferences
update-package Sitecore.Forms.Mvc.NoReferences
update-package Sitecore.Kernel.NoReferences
update-package Sitecore.Logging.NoReferences
update-package Sitecore.Marketing.NoReferences
update-package Sitecore.Marketing.Taxonomy.NoReferences
update-package Sitecore.Mvc.Analytics.NoReferences
update-package Sitecore.Mvc.NoReferences
update-package Sitecore.Publishing.WebDeploy.NoReferences
update-package Sitecore.Speak.Client.NoReferences
update-package Sitecore.WFFM.Abstractions.NoReferences
update-package Sitecore.WFFM.Actions.NoReferences
update-package Sitecore.Xdb.Configuration.NoReferences
